### ISSUE TITLE
lancement compris mais musique pas lancée

### ISSUE THREAD

**Issue by SebLeKlatz** [Sh1n1x/jarvis-youtube-musics-player#1]
Bonjour Sh1n1x,

je voudrais te faire part d'un souci rencontré lors de l'utilisation du plugin : la commande est reconnue, mais la musique ne se lance pas.
je précise que je n'ai pas trouvé de ticket sur ce sujet par ailleurs.
j'ai bien renstré l'API youtube entre les guillemets pendant la config

ci-dessous un troubleshooting :

lance la musique de kids united
$> echo "$(jv_pg_yt_ms_pl_search "${BASH_REMATCH[1]}")"
DEBUG: start_speaking hook
josette: Je lance la musique KIDS UNITED – Les lacs du Connemara (SARDOU et nous…)
DEBUG: using cache /dev/shm/je_lance_la_musique_kids_united_-_les_lacs_du_connemara_sardou_et_nous.mp3
DEBUG: stop_speaking hook
Seb: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain  -5 silence 1 0.1 10.1% 1 0.5 10.1% pad 0.5 0.5 trim 0 5
DEBUG: stop_listening hook
DEBUG: timeout, end of conversation
DEBUG: listening_timeout hook
DEBUG: exiting_cmd hook

je ne vois pas bien d'où peut provenir le problème. A ta dispo si besoin de plus de précisions.

merci

  PS : quand je mets le code avec "insert code', les sauts à la ligne disparaissent, rendant le texte illisible...peux tu me préciser stp comment faire un ticket propre, merci

**Comment by Sh1n1x** [comment]
Hello,

Tu utilises jarvis sur quoi comme machine raspberry pi ?

**Comment by SebLeKlatz** [comment]
oui dsl j'en oublie l'essentiel tellement je suis exité

josette tourne sous raspberry pi3
connexion ethermet (SFR)

**Comment by Sh1n1x** [comment]
Très bien, pas de soucis !

Peux-tu essayer de lancer la commande manuellement : 
`cvlc --play-and-exit --no-video https://www.youtube.com/watch?v=ayab7J9vZNs`

Et si ça fonctionne essaie voir de le lancer comme ça : 
`nohup cvlc --play-and-exit --no-video https://www.youtube.com/watch?v=ayab7J9vZNs`

Et si ça ne fonctionne pas peux-tu vérifier si tu as PulseAudio d'installé.

**Comment by SebLeKlatz** [comment]
ok j'essaie ça ce soir. Mes enceintes sont en jack, Pulseaudio semble permettre d'utiliser le bluetooth. Si je suis bien concerné par pulseaudio, je peux l'installer depuis la config? je ne trouve en ligne que des tartines de code pour l'installer

merci

**Comment by Sh1n1x** [comment]
Non en faite si tu as PulseAudio d'installé c'est sûrement ça qui fait merder le lancement de la musique via Cvlc. Il faut le désinstaller.

**Comment by SebLeKlatz** [comment]
alors pour les commandes manu il me sort ça 
>`pi@raspberrypi:~ $ cvlc --play-and-exit --no-video https://www.youtube.com/watch?v=ayab7J9vZNs
>bash: cvlc : commande introuvable`

et apparemment pas de  pulse audio à l'horizon
>`pi@raspberrypi:~ $ sudo apt-get autoremove pulseaudio
>Lecture des listes de paquets... Fait
>Construction de l'arbre des dépendances       
>Lecture des informations d'état... Fait
>Le paquet « pulseaudio » n'est pas installé, et ne peut donc être supprimé
> mis à jour, 0 nouvellement installés, 0 à enlever et 26 non mis à jour`

help stp 8(

**Comment by Sh1n1x** [comment]
Ah le plugin ne c'est pas installé il faut que tu fasses un `sudo apt-get install cvlc nohup`

**Comment by SebLeKlatz** [comment]
ah merde j'ai vu ton message trop tard j'ai installé entre temps vlc
`apt-get install vlc
`
et ça marche nikel!!

il faudrait peut être le préciser dans l'install pour les quiches dans mon genre

merci en tout cas!

**Comment by SebLeKlatz** [comment]
par contre difficile de lui faire comprendre "STOP" dans la commande "stop la musique"
et que je dis arrête ça crashe
`Seb: arrête la musique
/usr/local/bin/jarvis: eval: ligne 367: erreur de syntaxe près du symbole inattendu « ( »
/usr/local/bin/jarvis: eval: ligne 367: `killall vlc*DONNE*DEFINITION*DE (*)==say "Je me renseigne" && say "$(jv_pg_wk_search "${BASH_REMATCH[1]}")"'
josette: il y a eu une erreur
`

voir peut être pour d'autres déclencheurs pour arrêter la musique?

et tant qu'à faire, voir pour déclencher sur "je veux écouter..."

**Comment by Sh1n1x** [comment]
Normalement vlc doit s'installer directement avec le plugin. C'est bizarre.

Pour ton soucis d'arrêt de commande c'est étrange on dirait qu'il fusionné deux commandes. Essaie de mettre mon plugin en dernier dans l'ordre. Ça résoudra peut être le soucis

**Comment by SebLeKlatz** [comment]
je préfère pas, j'ai jeedom en dernier, le mettre plus haut capte toutes les commandes des plugins en dessous

**Comment by Sh1n1x** [comment]
Peux-tu du coup essayer de créer une commande du genre `*TEST STOP MUSIQUE*==killall vlc; say "C'est fait"` et de tester si cela fonctionne correctement

**Comment by SebLeKlatz** [comment]
il ne comprends pas cette commande. Peut être ambiguïté avec la commande native TEST ? J'ai essayé avec *MUSIQUE CA SUFFIT*, il ne comprend pas la commande non plus.

par contre il mélange les commandes avec celle d'origine : 
>arrête musique
>$> killall vlc*METEO*DEMAIN*==ww_forecast 2
>vlc*METEO*DEMAIN*==ww_forecast: aucun processus trouvé
>2: aucun processus trouvé

Sachant que le plugin méteo est classé juste après celui ci  dans mon "matching order"...

bizarre bizarre

edit : même en JARVIS-UI, aucune commande ne fonctionne, les 2 de base (stop, arrête la musique) ni la TEST que tu m'as indiquée. J'ai remonté l'ordre du plugin sans plus de résultat. Pour le moment la seule façon de stoper la musique est d'arrêter jarvis.

**Comment by Sh1n1x** [comment]
Ouai c'est ce qu'il m'a semblé. Essaie de rajouter un enter à la fin de mon fichier commands (dans le répertoire fr) et si ça fonctionne je ferai un update du plugin mais c'est étrange parce que chez moi ça marche sans soucis.

**Comment by SebLeKlatz** [comment]
ok par contre, par quel chemin j'accède à ce fichier sur pi stp, je ne suis pas encore bien familier avec ce matériel.

j'essaie ça ce soir, si mon pi me le permet, j'ai perdu du jour au lendemain la connexion (impossible de se connecter en http ou en SSH avec VNC......)

**Comment by SebLeKlatz** [comment]
alors, pi rétabli (le fait  de le mettre en IP fixe sur la box a foutu un beau bazar, peut être mal recopié l'adresse MAC, enfin bref)
je te confirme que mettre le plugin en dernier fonctionne avec la commande STOP (après avoir désactivé le plugin jeedom)
par contre, aucune idée pour la manière de modifier le fichier commands sur le pi, si tu veux bien m'indiquer la marche à suivre, je n'ai rien trouvé en ligne

merci!

**Comment by Sh1n1x** [comment]
Alors tu vas dans ton répertoire jarvis puis plugins_installed/jarvis-youtube-musics-player/fr/commands

**Comment by SebLeKlatz** [comment]
et ben bonne nouvelle, la musique se lance, s'arrête, nikel.
j'ai ajouté 4 retours à la ligne pour être sûr (j'ai l'impression qu'il y en avait déjà un).

si tu dois faire une mise à jour, j'ai une suggestion, il s'agirait de permettre les commandes :
je veux écouter
une musique de/ une chanson de

je sais que je peux le faire moi même avec le répertoire, mais je pense que ces modifs seraient écrasées avec une mise à jour officielle?

en tout cas merci bien

**Comment by Sh1n1x** [comment]
Ok j'ai fait l'update. du coup tu peux faire la mise à jour sans soucis et j'ai rajouté ton pattern pour la commande.

Oui si tu fais des modifs sur ton répertoire local elles vont être supprimées lors d'une màj
