### ISSUE TITLE
nouveaux patterns semblent inactifs

### ISSUE THREAD

**Issue by SebLeKlatz** [Sh1n1x/jarvis-youtube-musics-player#3]
salut @Sh1n1x 

les nouveaux pattern ne semblent pas répondre, je les vois bien dans commands, mais par au démarrage :

>Commands from plugin jarvis-youtube-musics-player:
>*LANCE*MUSIQUE (*)*	STOP*MUSIQUE|ARRET*MUSI 

et effectivement à la voix ou en UI, pas de résultat

bien à toi

**Comment by Sh1n1x** [comment]
Effectivement j'ai remis à jour en séparant par ligne :)

**Comment by SebLeKlatz** [comment]
salut @Sh1n1x 

il semble que les pattern restent inactif, je n'ai qu'eux au démarrage après mise à jour à l'instant : 
>Commands from plugin jarvis-youtube-musics-player:
>*LANCE*MUSIQUE (*)*	STOP*MUSIQUE|ARRET*MUSI

**Comment by SebLeKlatz** [comment]
très cher @Sh1n1x, après la nouvelle mise à jour ce soir, les pattern restent à ceux d'origine. Peut être un probleme de ma config?

merci

**Comment by SebLeKlatz** [comment]
@Sh1n1x , nouvelle mise à jour ce soir, toujours pas de nouveau pattern

peut être que le problème vient de chez moi?

**Comment by Sh1n1x** [comment]
Salut,

Je n'ai pas fait d'autre mise à jour depuis 7 jours. Tu dois confondre avec autre chose.

Concernant les commandes, celle-ci sont biens fonctionnelles sur mes 2 raspberry du coup je pense que c'est un soucis avec ta config. :/

**Comment by SebLeKlatz** [comment]
ah bizarre jarvis me propose une mise à jour du plugin à chaque démarrage depuis 2 ou 3 jours.
peut être mal installé??

je vais essayer de le désinstaller/réinstaller

merci

**Comment by SebLeKlatz** [comment]
au top! tout fonctionne normalement merci

j'ai juste désinstallé / réinstallé
