### ISSUE TITLE
Commande reconnue - pas de musique

### ISSUE THREAD

**Issue by Potjoe-97** [Sh1n1x/jarvis-youtube-musics-player#7]
Bonjour à tous ! 

Je rencontre des problèmes avec ce plugin.. En effet, si la commande est bien reconnue, la musique ne se lance pas. 

En termes de retour : rien en troubleshooting mode 
```
lance la musique you spin me round
$> echo "$(jv_pg_yt_ms_pl_search "${BASH_REMATCH[1]}")"
DEBUG: start_speaking hook "Je lance la musique Dead Or Alive - You Spin Me Round (Like a Record) (Official Video)"
Gladys: Je lance la musique Dead Or Alive - You Spin Me Round (Like a Record) (Official Video)
DEBUG: stop_speaking hook

```
Lorsque j'envoie la commande "arrete la musique", alors j'obtiens `mpv: aucun processus trouvé`.
Par contre, quand j'essaye de lancer à la main une musique via la commande `nohup mpv --no-video https://www.youtube.com/watch?v=6u3D80IV6lQ` là j'obtiens l'erreur suivante : 
```
nohup: les entrées sont ignorées et la sortie est ajoutée à 'nohup.out'
Erreur de segmentation
```

Une idée ?

**Comment by kptdobe** [comment]
J'ai fixé les scripts chez moi, la solution est dispo ici: https://github.com/Sh1n1x/jarvis-youtube-musics-player/pull/10

**Comment by Potjoe-97** [comment]
J'avais finalement fait un fix mais pas pensé à le soumettre... merci en tout cas !

**Comment by ghost** [comment]
> I finally made a fix but didn't think about submitting it ... thank you anyway!

Could your please share it with me so I can fix mine too?
